import React, {
  Suspense,
  useCallback,
  useEffect,
  useMemo,
  useRef,
} from "react";

import { Canvas, useFrame, useLoader } from "@react-three/fiber";
import * as THREE from "three";

import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import * as SkeletonUtils from "three/examples/jsm/utils/SkeletonUtils.js";

import { scrollStore } from "@/hooks/useScrollStore";

/* ============================================================
   ASSETS
   ============================================================ */

const BUTTERFLY_URL = "/models/butterfly.glb";

const BOUQUET_URL = "/models/sakura_cherry_big_edited.glb";

const JELLY_URLS = [
  "/textures/jelly_lilac.png",
  "/textures/jelly_azure.png",
  "/textures/jelly_rose.png",
];

const JELLY_ASPECT = [0.335, 0.383, 0.381];


/* ============================================================
   HELPERS
   ============================================================ */

const smoothstep = (edge0, edge1, x) => {
  const t = Math.min(
    1,
    Math.max(0, (x - edge0) / (edge1 - edge0))
  );

  return t * t * (3 - 2 * t);
};


/*
 * Frame-rate independent smoothing.
 */
const damp = (cur, target, k, delta) => {
  return (
    cur +
    (target - cur) *
      (1 - Math.exp(-k * delta))
  );
};


/* ============================================================
   HERO BOUQUET
   ============================================================ */

export const HeroBouquet = ({ rotationRef, visibleRef }) => {
  const gltf = useLoader(GLTFLoader, BOUQUET_URL);

  const groupRef = useRef(null);

  /*
   * Clone the model so it is safe to manipulate independently.
   */
  const clone = useMemo(() => {
    const cloned = SkeletonUtils.clone(gltf.scene);

    cloned.traverse((object) => {
      if (object.isMesh || object.isSkinnedMesh) {
        object.frustumCulled = true;

        /*
         * Clone materials as well.
         * This prevents future visual changes to the bouquet
         * from accidentally modifying another instance.
         */
        if (object.material) {
          object.material = object.material.clone();
        }
      }
    });

    return cloned;
  }, [gltf]);

  /*
   * Automatically normalize the model.
   *
   * This means your Blender export can be large or tiny and we
   * still bring it into a predictable size for the scene.
   */
  const norm = useMemo(() => {
    const box = new THREE.Box3().setFromObject(clone);

    const size = box.getSize(
      new THREE.Vector3()
    );

    const center = box.getCenter(
      new THREE.Vector3()
    );

    const maxDimension = Math.max(
      size.x,
      size.y,
      size.z
    );

    const scale =
      maxDimension > 0
        ? 2.90 / maxDimension
        : 1;

    return {
      scale,
      offsetX: -center.x,
      offsetY: -center.y,
      offsetZ: -center.z,
    };
  }, [clone]);

  /*
   * Reset the model's starting rotation whenever the model loads.
   */
  useEffect(() => {
    rotationRef.current.x = 0;
    rotationRef.current.y = 0;
    rotationRef.current.z = 0;
  }, [rotationRef]);

  /*
   * Frame loop.
   *
   * The bouquet itself has NO automatic rotation.
   * It only follows the rotation values coming from the
   * DOM interaction layer.
   */
  useFrame((_, delta) => {
    if (!groupRef.current) {
      return;
    }

    const targetOpacity = visibleRef.current;

    const currentOpacity =
      groupRef.current.userData.opacity ?? 0;

    const opacity = damp(
      currentOpacity,
      targetOpacity,
      7,
      delta
    );

    groupRef.current.userData.opacity =
      opacity;

    groupRef.current.visible =
      opacity > 0.01;

    /*
     * Fade all materials with the chapter.
     */
    groupRef.current.traverse((object) => {
      if (
        object.isMesh &&
        object.material
      ) {
        object.material.transparent = true;
        object.material.opacity = opacity;
      }
    });

    /*
     * Smoothly follow the rotation generated by
     * the interaction layer.
     */
    groupRef.current.rotation.x = damp(
      groupRef.current.rotation.x,
      rotationRef.current.x,
      14,
      delta
    );

    groupRef.current.rotation.y = damp(
      groupRef.current.rotation.y,
      rotationRef.current.y,
      14,
      delta
    );

    groupRef.current.rotation.z = damp(
      groupRef.current.rotation.z,
      rotationRef.current.z,
      14,
      delta
    );
  });

  return (
    <group
      ref={groupRef}
      visible={false}

      /*
       * FIXED 3D COORDINATES
       *
       * x = right side of hero
       * y = slightly above center
       * z = front/back position
       *
       * These are deliberately NOT based on scroll.
       */
      position={[1.9, 0.05, 0]}
    >
      <group
        scale={norm.scale}
      >
        <primitive
          object={clone}
          position={[
            norm.offsetX,
            norm.offsetY,
            norm.offsetZ,
          ]}
        />
      </group>
    </group>
  );
};


/* ============================================================
   INTERACTIVE BOUQUET MOUSE AREA
   ============================================================ */

/*
 * IMPORTANT:
 *
 * The main Canvas stays pointer-events-none so it doesn't
 * interfere with your website.
 *
 * This small DOM area sits exactly over the bouquet and owns
 * the mouse interaction.
 */
export const BouquetInteraction = ({ rotationRef }) => {
  const draggingRef = useRef(false);

  const pointerRef = useRef({
    x: 0,
    y: 0,
  });

  const onPointerDown = useCallback(
    (event) => {
      event.preventDefault();

      draggingRef.current = true;

      pointerRef.current.x =
        event.clientX;

      pointerRef.current.y =
        event.clientY;

      event.currentTarget.setPointerCapture(
        event.pointerId
      );
    },
    []
  );

  const onPointerMove = useCallback(
    (event) => {
      if (!draggingRef.current) {
        return;
      }

      const dx =
        event.clientX -
        pointerRef.current.x;

      const dy =
        event.clientY -
        pointerRef.current.y;

      pointerRef.current.x =
        event.clientX;

      pointerRef.current.y =
        event.clientY;

      /*
       * SHIFT = roll around Z.
       *
       * Normal drag:
       *   horizontal → Y rotation
       *   vertical   → X rotation
       *
       * Shift drag:
       *   horizontal → Z rotation
       */
      if (event.shiftKey) {
        rotationRef.current.z +=
          dx * 0.012;

        rotationRef.current.y +=
          dy * 0.004;
      } else {
        rotationRef.current.y +=
          dx * 0.012;

        rotationRef.current.x +=
          dy * 0.012;
      }

      /*
       * Keep values numerically sane.
       * There is no visual restriction here because rotation
       * naturally wraps around.
       */
      const max =
        Math.PI * 100;

      rotationRef.current.x =
        THREE.MathUtils.clamp(
          rotationRef.current.x,
          -max,
          max
        );

      rotationRef.current.y =
        THREE.MathUtils.clamp(
          rotationRef.current.y,
          -max,
          max
        );

      rotationRef.current.z =
        THREE.MathUtils.clamp(
          rotationRef.current.z,
          -max,
          max
        );
    },
    [rotationRef]
  );

  const releasePointer = useCallback(
    (event) => {
      draggingRef.current = false;

      if (
        event.currentTarget.hasPointerCapture?.(
          event.pointerId
        )
      ) {
        event.currentTarget.releasePointerCapture(
          event.pointerId
        );
      }
    },
    []
  );

  return (
    <div
      className="pointer-events-auto absolute z-[60] cursor-grab active:cursor-grabbing"

      /*
       * ========================================================
       * INTERACTION AREA POSITION
       * ========================================================
       *
       * This is the SCREEN position of the bouquet interaction
       * area.
       *
       * Adjust these values later if needed.
       */
      style={{
        width: "420px",
        height: "520px",
        right: "6vw",
        top: "17vh",

        /*
         * Don't let this area accidentally block the rest
         * of the site.
         */
        touchAction: "none",
      }}

      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={releasePointer}
      onPointerCancel={releasePointer}

      aria-label="Interactive flower bouquet"
      role="img"
    >
      {/* Invisible interaction surface */}
    </div>
  );
};


/* ============================================================
   BUTTERFLY
   ============================================================ */

const Butterfly = ({
  gltf,
  norm,
  seed = 0,
}) => {
  const pathRef = useRef();

  const clone = useMemo(() => {
    const c =
      SkeletonUtils.clone(
        gltf.scene
      );

    c.traverse((o) => {
      if (
        o.isMesh ||
        o.isSkinnedMesh
      ) {
        o.frustumCulled = false;
        o.material.transparent = true;
      }
    });

    return c;
  }, [gltf]);

  const mixer = useMemo(
    () =>
      new THREE.AnimationMixer(
        clone
      ),
    [clone]
  );

  const rand = useMemo(
    () => ({
      r:
        1.6 +
        (seed % 5) *
          0.35,

      hs:
        0.4 +
        ((seed * 0.13) %
          0.4),

      off:
        seed * 0.9,

      yOff:
        (seed % 3) *
          0.6 -
        0.4,

      scale:
        0.8 +
        (seed % 3) *
          0.14,
    }),
    [seed]
  );

  useEffect(() => {
    const clip =
      gltf.animations.find(
        (a) =>
          a.name ===
          "Flying"
      ) ||
      gltf.animations[0];

    if (!clip) {
      return;
    }

    const action =
      mixer.clipAction(
        clip
      );

    action.timeScale =
      0.85 +
      (seed % 4) *
        0.18;

    action.time =
      (seed * 0.37) %
      clip.duration;

    action.play();

    return () =>
      mixer.stopAllAction();
  }, [
    mixer,
    gltf,
    seed,
  ]);

  useFrame(
    (state, delta) => {
      mixer.update(delta);

      const t =
        state.clock.elapsedTime +
        rand.off;

      if (
        pathRef.current
      ) {
        pathRef.current.position.set(
          Math.cos(
            t * rand.hs
          ) *
            rand.r,

          Math.sin(
            t *
              rand.hs *
              1.3
          ) *
            0.6 +
            rand.yOff,

          Math.sin(
            t *
              rand.hs *
              0.7
          ) *
            0.8
        );

        const vx =
          -Math.sin(
            t * rand.hs
          ) *
          rand.hs *
          rand.r;

        const vz =
          Math.cos(
            t *
              rand.hs *
              0.7
          ) *
          0.7 *
          rand.hs *
          0.8;

        pathRef.current.rotation.y =
          Math.atan2(
            vx,
            vz
          );

        pathRef.current.rotation.z =
          Math.sin(
            t * rand.hs
          ) *
          0.25;

        pathRef.current.rotation.x =
          Math.sin(
            t *
              rand.hs *
              1.3
          ) *
          0.12;
      }
    }
  );

  return (
    <group ref={pathRef}>
      <group
        scale={
          norm.s *
          rand.scale
        }
      >
        <primitive
          object={clone}
          position={[
            norm.offX,
            norm.offY,
            norm.offZ,
          ]}
        />
      </group>
    </group>
  );
};


/* ============================================================
   BUTTERFLIES
   ============================================================ */

const Butterflies = ({
  visibleRef,
}) => {
  const gltf =
    useLoader(
      GLTFLoader,
      BUTTERFLY_URL
    );

  const groupRef =
    useRef();

  const norm =
    useMemo(() => {
      const box =
        new THREE.Box3()
          .setFromObject(
            gltf.scene
          );

      const size =
        box.getSize(
          new THREE.Vector3()
        );

      const center =
        box.getCenter(
          new THREE.Vector3()
        );

      const s =
        0.85 /
        Math.max(
          size.x,
          size.y,
          size.z
        );

      return {
        s,
        offX:
          -center.x,
        offY:
          -center.y,
        offZ:
          -center.z,
      };
    }, [gltf]);

  useFrame(
    (_, delta) => {
      if (
        !groupRef.current
      ) {
        return;
      }

      const target =
        visibleRef.current;

      const cur =
        groupRef.current
          .userData
          .op ?? 0;

      const next =
        damp(
          cur,
          target,
          5,
          delta
        );

      groupRef.current
        .userData
        .op = next;

      groupRef.current.visible =
        next > 0.01;

      groupRef.current.traverse(
        (o) => {
          if (
            o.isMesh &&
            o.material
          ) {
            o.material.transparent =
              true;

            o.material.opacity =
              Math.min(
                1,
                next
              );
          }
        }
      );

      groupRef.current.position.y =
        (1 - next) *
        -1.5;
    }
  );

  return (
    <group
      ref={groupRef}
      visible={false}
    >
      {[
        1,
        2,
        3,
        4,
        5,
        6,
        7,
      ].map((s) => (
        <Butterfly
          key={s}
          gltf={gltf}
          norm={norm}
          seed={s}
        />
      ))}
    </group>
  );
};


/* ============================================================
   JELLYFISH
   ============================================================ */

const SWARM = [
  {
    x: -3.4,
    y: 1.2,
    z: -1.8,
    s: 0.7,
    sp: 0.32,
  },
  {
    x: -2.2,
    y: -1.0,
    z: -0.6,
    s: 1.05,
    sp: 0.26,
  },
  {
    x: -0.8,
    y: 1.6,
    z: -2.2,
    s: 0.6,
    sp: 0.4,
  },
  {
    x: 0.3,
    y: -1.5,
    z: -1.0,
    s: 0.9,
    sp: 0.3,
  },
  {
    x: 1.2,
    y: 0.9,
    z: 0.3,
    s: 1.2,
    sp: 0.22,
  },
  {
    x: 2.4,
    y: -0.5,
    z: -1.8,
    s: 0.65,
    sp: 0.36,
  },
  {
    x: 3.3,
    y: 1.3,
    z: -0.9,
    s: 0.85,
    sp: 0.28,
  },
  {
    x: 3.7,
    y: -1.4,
    z: -2.4,
    s: 0.55,
    sp: 0.42,
  },
  {
    x: -1.6,
    y: 0.1,
    z: 0.6,
    s: 1.0,
    sp: 0.24,
  },
];

const JellyBillboard = ({
  cfg,
  tex,
  aspect,
  seed,
}) => {
  const ref =
    useRef();

  const h =
    2.5 * cfg.s;

  const w =
    h * aspect;

  useFrame(
    (state) => {
      const t =
        state.clock.elapsedTime +
        seed * 2.1;

      const pulse =
        Math.sin(
          t * 1.4
        );

      if (ref.current) {
        ref.current.position.set(
          cfg.x +
            Math.sin(
              t *
                cfg.sp
            ) *
              0.5,

          cfg.y +
            Math.cos(
              t *
                cfg.sp *
                0.8
            ) *
              0.6 +
            pulse *
              0.06,

          cfg.z
        );

        ref.current.rotation.z =
          Math.sin(
            t * 0.35
          ) * 0.11;

        ref.current.scale.set(
          w *
            (1 -
              pulse *
                0.06),

          h *
            (1 +
              pulse *
                0.07),

          1
        );
      }
    }
  );

  return (
    <mesh
      ref={ref}
      position={[
        cfg.x,
        cfg.y,
        cfg.z,
      ]}
    >
      <planeGeometry
        args={[1, 1]}
      />

      <meshBasicMaterial
        map={tex}
        transparent
        depthWrite={false}
        blending={
          THREE.NormalBlending
        }
        opacity={0}
        toneMapped={false}
        alphaTest={0.01}
      />
    </mesh>
  );
};


const Jellies = ({
  visibleRef,
}) => {
  const textures =
    useLoader(
      THREE.TextureLoader,
      JELLY_URLS
    );

  useMemo(() => {
    textures.forEach(
      (texture) => {
        texture.colorSpace =
          THREE.SRGBColorSpace;

        texture.minFilter =
          THREE.LinearFilter;
      }
    );
  }, [textures]);

  const groupRef =
    useRef();

  useFrame(
    (_, delta) => {
      if (
        !groupRef.current
      ) {
        return;
      }

      const target =
        visibleRef.current;

      const cur =
        groupRef.current
          .userData
          .op ?? 0;

      const next =
        damp(
          cur,
          target,
          5,
          delta
        );

      groupRef.current
        .userData
        .op = next;

      groupRef.current.visible =
        next > 0.01;

      groupRef.current.traverse(
        (o) => {
          if (
            o.isMesh &&
            o.material
          ) {
            o.material.opacity =
              next;
          }
        }
      );
    }
  );

  return (
    <group
      ref={groupRef}
      visible={false}
    >
      {SWARM.map(
        (cfg, i) => (
          <JellyBillboard
            key={i}
            cfg={cfg}
            tex={
              textures[
                i % 3
              ]
            }
            aspect={
              JELLY_ASPECT[
                i % 3
              ]
            }
            seed={i + 1}
          />
        )
      )}
    </group>
  );
};


/* ============================================================
   PETAL SHOWER
   ============================================================ */

const PetalShower = ({
  activeRef,
}) => {
  const meshRef =
    useRef();

  const count = 320;

  const dummy =
    useMemo(
      () =>
        new THREE.Object3D(),
      []
    );

  const petals =
    useMemo(
      () =>
        Array.from(
          { length: count },
          () => ({
            x:
              (Math.random() -
                0.5) *
              12,

            y:
              3 +
              Math.random() *
                7,

            z:
              (Math.random() -
                0.5) *
              6,

            vy:
              0.22 +
              Math.random() *
                0.45,

            vx:
              (Math.random() -
                0.5) *
              0.12,

            rot:
              Math.random() *
              Math.PI *
              2,

            vr:
              (Math.random() -
                0.5) *
              0.05,

            scale:
              0.18 +
              Math.random() *
                0.22,
          })
        ),
      []
    );

  useFrame(
    (_, delta) => {
      if (
        !meshRef.current
      ) {
        return;
      }

      const active =
        activeRef.current;

      const cur =
        meshRef.current
          .userData
          .op ?? 0;

      const next =
        damp(
          cur,
          active,
          4,
          delta
        );

      meshRef.current
        .userData
        .op = next;

      meshRef.current.visible =
        next > 0.01;

      if (
        meshRef.current.material
      ) {
        meshRef.current.material.transparent =
          true;

        meshRef.current.material.opacity =
          Math.min(
            1,
            next
          );
      }

      petals.forEach(
        (p, i) => {
          p.y -=
            p.vy *
            delta *
            (0.6 +
              active);

          p.x += p.vx;

          p.rot += p.vr;

          if (
            p.y < -4
          ) {
            p.y =
              4 +
              Math.random() *
                3;

            p.x =
              (Math.random() -
                0.5) *
              12;
          }

          dummy.position.set(
            p.x,
            p.y,
            p.z
          );

          dummy.rotation.set(
            p.rot * 0.5,
            p.rot * 0.3,
            p.rot
          );

          dummy.scale.setScalar(
            p.scale
          );

          dummy.updateMatrix();

          meshRef.current.setMatrixAt(
            i,
            dummy.matrix
          );
        }
      );

      meshRef.current.instanceMatrix.needsUpdate =
        true;
    }
  );

  return (
    <instancedMesh
      ref={meshRef}
      args={[
        null,
        null,
        count,
      ]}
      visible={false}
    >
      <planeGeometry
        args={[0.5, 0.7]}
      />

      <meshStandardMaterial
        color="#F2B33A"
        side={THREE.DoubleSide}
        transparent
        opacity={0}
        emissive="#FFCF6B"
        emissiveIntensity={0.35}
      />
    </instancedMesh>
  );
};


/* ============================================================
   SCENE ORCHESTRATOR
   ============================================================ */

const SceneOrchestrator = () => {
  const btfRef =
    useRef(0);

  const jfRef =
    useRef(0);

  const petalRef =
    useRef(0);

  useFrame(
    ({ camera, clock }, delta) => {
      const {
        sectionIndex,
        sectionProgress,
      } =
        scrollStore.get();

      const chapterProgress =
        (index) =>
          sectionIndex < index
            ? 0
            : sectionIndex > index
              ? 1
              : sectionProgress;

      /*
       * ========================================================
       * EXISTING CHAPTER EFFECTS
       * ========================================================
       */

      const butterflyProgress =
        chapterProgress(2);

      const jellyfishProgress =
        chapterProgress(3);

      const finaleProgress =
        chapterProgress(5);

      btfRef.current =
        smoothstep(
          0.05,
          0.2,
          butterflyProgress
        ) *
        (1 -
          smoothstep(
            0.78,
            0.98,
            butterflyProgress
          ));

      jfRef.current =
        smoothstep(
          0.05,
          0.2,
          jellyfishProgress
        ) *
        (1 -
          smoothstep(
            0.78,
            0.98,
            jellyfishProgress
          ));

      petalRef.current =
        smoothstep(
          0.1,
          0.55,
          finaleProgress
        );


      /*
       * ========================================================
       * CAMERA
       * ========================================================
       */

      const targetZ =
        5.5 -
        smoothstep(
          0.1,
          0.8,
          finaleProgress
        ) *
          1.2;

      const targetY =
        0.4 +
        Math.sin(
          clock.elapsedTime *
            0.2
        ) *
          0.05;

      camera.position.z =
        damp(
          camera.position.z,
          targetZ,
          2.5,
          delta
        );

      camera.position.y =
        damp(
          camera.position.y,
          targetY,
          3,
          delta
        );

      camera.lookAt(
        0,
        0.4,
        0
      );
    }
  );

  return (
    <>
      {/* ========================================================
          LIGHTING
          ======================================================== */}

      <ambientLight
        intensity={0.85}
        color="#FDFBF7"
      />

      <directionalLight
        position={[
          3,
          5,
          4,
        ]}
        intensity={1.1}
        color="#F2A68D"
      />

      <directionalLight
        position={[
          -3,
          2,
          4,
        ]}
        intensity={0.4}
        color="#DCD0FF"
      />


      {/* ========================================================
          HERO BOUQUET
          ======================================================== */}


      {/* ========================================================
          EXISTING BUTTERFLIES
          ======================================================== */}

      <Suspense fallback={null}>
        <Butterflies
          visibleRef={btfRef}
        />
      </Suspense>


      {/* ========================================================
          EXISTING JELLYFISH
          ======================================================== */}

      <Suspense fallback={null}>
        <Jellies
          visibleRef={jfRef}
        />
      </Suspense>


      {/* ========================================================
          EXISTING PETALS
          ======================================================== */}

      <PetalShower
        activeRef={petalRef}
      />
    </>
  );
};


/* ============================================================
   MAIN SCENE
   ============================================================ */

export const HeroBouquetScene = ({ rotationRef, visibleRef }) => {
  return (
    <div
      className="pointer-events-none absolute inset-0 z-[20]"
      aria-hidden="true"
      data-testid="hero-bouquet-scene"
    >
      <Canvas
        camera={{ position: [0, 0.4, 5.5], fov: 42 }}
        gl={{
          antialias: true,
          alpha: true,
          powerPreference: "high-performance",
        }}
        dpr={[1, 1.6]}
      >
        <ambientLight intensity={0.85} color="#FDFBF7" />
        <directionalLight position={[3, 5, 4]} intensity={1.1} color="#F2A68D" />
        <directionalLight position={[-3, 2, 4]} intensity={0.4} color="#DCD0FF" />

        <Suspense fallback={null}>
          <HeroBouquet
            rotationRef={rotationRef}
            visibleRef={visibleRef}
          />
        </Suspense>
      </Canvas>
    </div>
  );
};

const Scene3D = () => {
  return (
    <div
      className="pointer-events-none fixed inset-0 z-[5]"
      aria-hidden="true"
      data-testid="scene-3d-canvas"
    >
      <Canvas
        camera={{ position: [0, 0.4, 5.5], fov: 42 }}
        gl={{
          antialias: true,
          alpha: true,
          powerPreference: "high-performance",
        }}
        dpr={[1, 1.6]}
      >
        <SceneOrchestrator />
      </Canvas>
    </div>
  );
};

export default Scene3D;
